### PR TITLE
Add emacs-tree-sitter-module to OS path.

### PR DESCRIPTION
**Pull request by noalias**

### CODE REVIEW

**Comment by iquiw** [comment]
Hmm, could you  let me know why it is required?
I can use these tree-sitter modules without adding the directory to PATH.

**Comment by noalias** [comment]
When add the directory emacs-tree-sitter-module to OS path, you do not need to set the variable `treesit-extra-load-path` in your emacs config files.
Perhaps it depends on personal habits.

**Comment by iquiw** [comment]
I see. I am using `treesit-extra-load-path`.

I'd like to avoid adding the directory to PATH, as searching executable from PATH is slow on my Windows environments.

**Comment by iquiw** [comment]
@noalias Thank you for the pull request, sorry!

**Pull request closed without merging**
